// <auto-generated />
namespace _92031083_ModelRailStore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class update_scale_params : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_scale_params));
        
        string IMigrationMetadata.Id
        {
            get { return "202101210401292_update_scale_params"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
